### ISSUE TITLE
CLANG Compiler Error

### ISSUE THREAD

**Issue by aleneum** [tik0/rsb_ws_bridge#1]
First things first: Great work, thx! Now business:

If you use clang as a compiler, the build process will not work due to the '-std=c++11' flag which is also passed to the C-Version of clang. The build fails with:

``` bash
$ make
[ 50%] Building C object CMakeFiles/build.dir/mongoose/mongoose.c.o
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
make[2]: *** [CMakeFiles/build.dir/mongoose/mongoose.c.o] Error 1
make[1]: *** [CMakeFiles/build.dir/all] Error 2
make: *** [all] Error 2
```

The fix is easy though. Just replace the last line in your CMakeLists.txt

``` cmake
ADD_DEFINITIONS (-Wall -Wno-deprecated-declarations -O2 -Wno-write-strings -std=c++11)
```

with

``` cmake
ADD_DEFINITIONS (-Wall -Wno-deprecated-declarations -O2 -Wno-write-strings)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11"
```

Best regards,
Alex

**Comment by tik0** [comment]
Thanks for noticing this.
I just fixed this.
